# Generated by Django 4.2.4 on 2023-08-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=512, unique=True)),
                ('channel_title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('status', models.CharField(default='New', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=512, unique=True)),
                ('video_name', models.CharField(blank=True, max_length=512, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=512, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
