from django.db import models


class SafeSearch(models.TextChoices):
    moderate = 'moderate', 'moderate'
    none = 'none', 'without filter'
    strict = 'strict', 'strict'


class ChannelType(models.TextChoices):
    any_v = 'any', 'any'
    show = 'show', 'show'


class VideoCaption(models.TextChoices):
    any_v = 'any', 'any'
    closed_caption = 'closedCaption', 'closed caption'
    none_caption = 'none', 'without a caption'


class VideoDefinition(models.TextChoices):
    any_v = 'any', 'any'
    high = 'high', 'only HD videos'
    standard = 'standard', 'videos in standard definition'


class VideoDimension(models.TextChoices):
    any_v = 'any', 'any'
    v_2d = '2d', 'exclude 3D videos'
    v_3d = '3d', 'only include 3D videos'


class VideoEmbeddable(models.TextChoices):
    any_v = 'any', 'any'
    embeddable = 'true', 'embeddable'


class VideoLicense(models.TextChoices):
    any_v = 'any', 'any'
    creative_common = 'creativeCommon', 'Creative Commons'
    youtube = 'youtube', 'YouTube'


class VideoPaidProductPlacement(models.TextChoices):
    any_v = 'any', 'any'
    true = 'true', 'with paid promotions'


class VideoSyndicated(models.TextChoices):
    any_v = 'any', 'any'
    true = 'true', 'syndicated videos'


class VideoType(models.TextChoices):
    any_v = 'any', 'any'
    episode = 'episode', 'episodes of shows'
    movie = 'movie', 'movies'


class Languages(models.TextChoices):
    none = '', '-'
    af = 'af', 'Afrikaans'
    am = 'am', 'Amharic'
    ar = 'ar', 'Arabic'
    assam = 'as', 'Assamese'
    az = 'az', 'Azerbaijani'
    be = 'be', 'Belarusian'
    bg = 'bg', 'Bulgarian'
    bn = 'bn', 'Bengali'
    bs = 'bs', 'Bosnian'
    ca = 'ca', 'Catalan'
    cs = 'cs', 'Czech'
    da = 'da', 'Danish'
    de = 'de', 'German'
    el = 'el', 'Greek'
    en_GB = 'en-GB', 'English(UK)'
    en_IN = 'en-IN', 'English(India)'
    en = 'en', 'English(US)'
    es = 'es', 'Spanish'
    es_419 = 'es-419', 'Spanish(Latin America)'
    es_US = 'es-US', 'Spanish(US)'
    et = 'et', 'Estonian'
    eu = 'eu', 'Basque'
    fa = 'fa', 'Persian(Farsi)'
    fi = 'fi', 'Finnish'
    fil = 'fil', 'Filipino'
    fr_CA = 'fr-CA', 'French(Canada)'
    fr = 'fr', 'French(France)'
    gl = 'gl', 'Galician'
    gu = 'gu', 'Gujarati'
    hi = 'hi', 'Hindi'
    hr = 'hr', 'Croatian'
    hu = 'hu', 'Hungarian'
    hy = 'hy', 'Armenian'
    id = 'id = Indonesian', 'Indonesian'
    ic = 'is = Icelandic', 'Icelandic'
    it = 'it', 'Italian'
    iw = 'iw', 'Hebrew'
    ja = 'ja', 'Japanese'
    ka = 'ka', 'Georgian'
    kk = 'kk', 'Kazakh'
    km = 'km', 'Khmer(Cambodian)'
    kn = 'kn', 'Kannada'
    ko = 'ko', 'Korean'
    ky = 'ky', 'Kyrgyz'
    lo = 'lo', 'Lao'
    lt = 'lt', 'Lithuanian'
    lv = 'lv', 'Latvian'
    mk = 'mk', 'Macedonian'
    ml = 'ml', 'Malayalam'
    mn = 'mn', 'Mongolian'
    mr = 'mr', 'Marathi'
    ms = 'ms', 'Malay'
    my = 'my', 'Burmese'
    ne = 'ne', 'Nepali'
    nl = 'nl', 'Dutch'
    no = 'no', 'Norwegian'
    od = 'or', 'Odia(Oriya)'
    pa = 'pa', 'Punjabi'
    pl = 'pl', 'Polish'
    pt = 'pt ', 'Portuguese'
    pt_PT = 'pt-PT', 'Portuguese(Portugal)'
    ro = 'ro', 'Romanian'
    ru = 'ru', 'Russian'
    si = 'si', 'Sinhala(Sinhalese)'
    sk = 'sk', 'Slovak'
    sl = 'sl', 'Slovenian'
    sq = 'sq', 'Albanian'
    sr_Latn = 'sr-Latn', 'Serbian(Latin)'
    sr = 'sr', 'Serbian(Cyrillic)'
    sv = 'sv', 'Swedish'
    sw = 'sw', 'Swahili'
    ta = 'ta', 'Tamil'
    te = 'te', 'Telugu'
    th = 'th', 'Thai'
    tr = 'tr', 'Turkish'
    uk = 'uk', 'Ukrainian'
    ur = 'ur', 'Urdu'
    uz = 'uz', 'Uzbek'
    vi = 'vi', 'Vietnamese'
    zh_CN = 'zh-CN', 'Chinese(Simplified, China)'
    zh_HK = 'zh-HK', 'Chinese(Traditional, Hong Kong)'
    zh_TW = 'zh-TW', 'Chinese(Traditional, Taiwan)'
    zu = 'zu', 'Zulu'


class Category(models.TextChoices):
    none = '', '-'
    film_animation = '1', 'Film & Animation'
    autos_and_vehicles = '2', 'Autos & Vehicles'
    music = '10', 'Music'
    pets_and_animals = '15', 'Pets & Animals'
    sports = '17', 'Sports'
    short_movies = '18', 'Short Movies'
    travel_and_events = '19', 'Travel & Events'
    gaming = '20', 'Gaming'
    videoblogging = '21', 'Videoblogging'
    people_and_blogs = '22', 'People & Blogs'
    comedy = '23', 'Comedy'
    entertainment = '24', 'Entertainment'
    news_and_politics = '25', 'News & Politics'
    howto_and_style = '26', 'Howto & Style'
    education = '27', 'Education'
    science_and_technology = '28', 'Science & Technology'
    movies = '30', 'Movies'
    anime_and_animation = '31', 'Anime / Animation'
    action_and_adventure = '32', 'Action / Adventure'
    classics = '33', 'Classics'
    comedy_ = '34', 'Comedy'
    documentary = '35', 'Documentary'
    drama = '36', 'Drama'
    family = '37', 'Family'
    foreign = '38', 'Foreign'
    horror = '39', 'Horror'
    sci_fi_and_fantasy = '40', 'Sci - Fi / Fantasy'
    thriller = '41', 'Thriller'
    shorts = '42', 'Shorts'
    shows = '43', 'Shows'
    trailers = '44', 'Trailers'


class Region(models.TextChoices):
    none = '', '-'
    AE = 'AE', 'United Arab Emirates'
    BH = 'BH', 'Bahrain'
    DZ = 'DZ', 'Algeria'
    EG = 'EG', 'Egypt'
    IQ = 'IQ', 'Iraq'
    JO = 'JO', 'Jordan'
    KW = 'KW', 'Kuwait'
    LB = 'LB', 'Lebanon'
    LY = 'LY', 'Libya'
    MA = 'MA', 'Morocco'
    OM = 'OM', 'Oman'
    QA = 'QA', 'Qatar'
    SA = 'SA', 'Saudi Arabia'
    TN = 'TN', 'Tunisia'
    YE = 'YE', 'Yemen'
    AZ = 'AZ', 'Azerbaijan'
    BY = 'BY', 'Belarus'
    BG = 'BG', 'Bulgaria'
    BD = 'BD', 'Bangladesh'
    BA = 'BA', 'Bosnia and Herzegovina'
    CZ = 'CZ', 'Czech Republic'
    DK = 'DK', 'Denmark'
    AT = 'AT', 'Austria'
    CH = 'CH', 'Switzerland'
    DE = 'DE', 'Germany'
    GR = 'GR', 'Greece'
    AU = 'AU', 'Australia'
    BE = 'BE', 'Belgium'
    CA = 'CA', 'Canada'
    GB = 'GB', 'United Kingdom'
    GH = 'GH', 'Ghana'
    IE = 'IE', 'Ireland'
    IL = 'IL', 'Israel'
    IN = 'IN', 'India'
    JM = 'JM', 'Jamaica'
    KE = 'KE', 'Kenya'
    MT = 'MT', 'Malta'
    NG = 'NG', 'Nigeria'
    NZ = 'NZ', 'New Zealand'
    SG = 'SG', 'Singapore'
    UG = 'UG', 'Uganda'
    US = 'US', 'United States'
    ZA = 'ZA', 'South Africa'
    ZW = 'ZW', 'Zimbabwe'
    AR = 'AR', 'Argentina'
    BO = 'BO', 'Bolivia'
    CL = 'CL', 'Chile'
    CO = 'CO', 'Colombia'
    CR = 'CR', 'Costa Rica'
    DO = 'DO', 'Dominican Republic'
    EC = 'EC', 'Ecuador'
    ES = 'ES', 'Spain'
    GT = 'GT', 'Guatemala'
    HN = 'HN', 'Honduras'
    MX = 'MX', 'Mexico'
    NI = 'NI', 'Nicaragua'
    PA = 'PA', 'Panama'
    PE = 'PE', 'Peru'
    PR = 'PR', 'Puerto Rico'
    PY = 'PY', 'Paraguay'
    SV = 'SV', 'El Salvador'
    UY = 'UY', 'Uruguay'
    VE = 'VE', 'Venezuela'
    EE = 'EE', 'Estonia'
    FI = 'FI', 'Finland'
    PH = 'PH', 'Philippines'
    FR = 'FR', 'France'
    SN = 'SN', 'Senegal'
    HR = 'HR', 'Croatia'
    HU = 'HU', 'Hungary'
    ID = 'ID', 'Indonesia'
    IS = 'IS', 'Iceland'
    IT = 'IT', 'Italy'
    JP = 'JP', 'Japan'
    GE = 'GE', 'Georgia'
    KZ = 'KZ', 'Kazakhstan'
    KR = 'KR', 'South Korea'
    LU = 'LU', 'Luxembourg'
    LA = 'LA', 'Laos'
    LT = 'LT', 'Lithuania'
    LV = 'LV', 'Latvia'
    MK = 'MK', 'North Macedonia'
    MY = 'MY', 'Malaysia'
    NO = 'NO', 'Norway'
    NP = 'NP', 'Nepal'
    NL = 'NL', 'Netherlands'
    PL = 'PL', 'Poland'
    BR = 'BR', 'Brazil'
    PT = 'PT', 'Portugal'
    RO = 'RO', 'Romania'
    RU = 'RU', 'Russia'
    LK = 'LK', 'Sri Lanka'
    SK = 'SK', 'Slovakia'
    SI = 'SI', 'Slovenia'
    ME = 'ME', 'Montenegro'
    RS = 'RS', 'Serbia'
    SE = 'SE', 'Sweden'
    TZ = 'TZ', 'Tanzania'
    TH = 'TH', 'Thailand'
    TR = 'TR', 'Turkey'
    UA = 'UA', 'Ukraine'
    PK = 'PK', 'Pakistan'
    VN = 'VN', 'Vietnam'
    HK = 'HK', 'Hong Kong'
    TW = 'TW', 'Taiwan'
    CY = 'CY', 'Cyprus'
    KH = 'KH', 'Cambodia'
    LI = 'LI', 'Liechtenstein'
    PG = 'PG', 'Papua New Guinea'


class Topics(models.TextChoices):
    none = '', '-'
    m_04rlf = '/m/04rlf', 'Music (parent topic)'
    m_02mscn = '/m/02mscn', 'Christian music'
    m_0ggq0m = '/m/0ggq0m', 'Classical music'
    m_01lyv = '/m/01lyv', 'Country'
    m_02lkt = '/m/02lkt', 'Electronic music'
    m_0glt670 = '/m/0glt670', 'Hip hop music'
    m_05rwpb = '/m/05rwpb', 'Independent music'
    m_03_d0 = '/m/03_d0', 'Jazz'
    m_028sqc = '/m/028sqc', 'Music of Asia'
    m_0g293 = '/m/0g293', 'Music of Latin America'
    m_064t9 = '/m/064t9', 'Pop music'
    m_06cqb = '/m/06cqb', 'Reggae'
    m_06j6l = '/m/06j6l', 'Rhythm and blues'
    m_06by7 = '/m/06by7', 'Rock music'
    m_0gywn = '/m/0gywn', 'Soul music'
    m_0bzvm2 = '/m/0bzvm2', 'Gaming (parent topic)'
    m_025zzc = '/m/025zzc', 'Action game'
    m_02ntfj = '/m/02ntfj', 'Action-adventure game'
    m_0b1vjn = '/m/0b1vjn', 'Casual game'
    m_02hygl = '/m/02hygl', 'Music video game'
    m_04q1x3q = '/m/04q1x3q', 'Puzzle video game'
    m_01sjng = '/m/01sjng', 'Racing video game'
    m_0403l3g = '/m/0403l3g', 'Role-playing video game'
    m_021bp2 = '/m/021bp2', 'Simulation video game'
    m_022dc6 = '/m/022dc6', 'Sports game'
    m_03hf_rm = '/m/03hf_rm', 'Strategy video game'
    m_06ntj = '/m/06ntj', 'Sports (parent topic)'
    m_0jm_ = '/m/0jm_', 'American football'
    m_018jz = '/m/018jz', 'Baseball'
    m_018w8 = '/m/018w8', 'Basketball'
    m_01cgz = '/m/01cgz', 'Boxing'
    m_09xp_ = '/m/09xp_', 'Cricket'
    m_02vx4 = '/m/02vx4', 'Football'
    m_037hz = '/m/037hz', 'Golf'
    m_03tmr = '/m/03tmr', 'Ice hockey'
    m_01h7lh = '/m/01h7lh', 'Mixed martial arts'
    m_0410tth = '/m/0410tth', 'Motorsport'
    m_07bs0 = '/m/07bs0', 'Tennis'
    m_07_53 = '/m/07_53', 'Volleyball'
    m_02jjt = '/m/02jjt', 'Entertainment (parent topic)'
    m_09kqc = '/m/09kqc', 'Humor'
    m_02vxn = '/m/02vxn', 'Movies'
    m_05qjc = '/m/05qjc', 'Performing arts'
    m_066wd = '/m/066wd', 'Professional wrestling'
    m_0f2f9 = '/m/0f2f9', 'TV shows'
    m_019_rr = '/m/019_rr', 'Lifestyle (parent topic)'
    m_032tl = '/m/032tl', 'Fashion'
    m_027x7n = '/m/027x7n', 'Fitness'
    m_02wbm = '/m/02wbm', 'Food'
    m_03glg = '/m/03glg', 'Hobby'
    m_068hy = '/m/068hy', 'Pets'
    m_041xxh = '/m/041xxh', 'Physical attractiveness [Beauty]'
    m_07c1v = '/m/07c1v', 'Technology'
    m_07bxq = '/m/07bxq', 'Tourism'
    m_07yv9 = '/m/07yv9', 'Vehicles'
    m_098wr = '/m/098wr', 'Society (parent topic)'
    m_09s1f = '/m/09s1f', 'Business'
    m_0kt51 = '/m/0kt51', 'Health'
    m_01h6rj = '/m/01h6rj', 'Military'
    m_05qt0 = '/m/05qt0', 'Politics'
    m_06bvp = '/m/06bvp', 'Religion'
    m_01k8wb = '/m/01k8wb', 'Knowledg'
